apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      keptn.sh/workload: gmod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        keptn.sh/app: gmod-app
        keptn.sh/workload: gmod
        keptn.sh/version: {{ .Values.image.tag }}
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets: {{ .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{ end }}
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources: {{ .Values.resources | toYaml | nindent 10 }}
        {{ if .Values.args }}
        args: {{ .Values.args | toYaml | nindent 10 }}
        {{ end }}
        ports:
        {{ range $portName, $portConfig := .Values.ports -}}
        - containerPort: {{ $portConfig.port }}
          name: {{ $portName }}
        {{ end }}
        volumeMounts:
        - mountPath: /gmod
          name: config

      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
       

