{{ if .Values.ingress.enabled }}
{{ if eq .Values.ingress.provider "kong" }}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: kong-gateway-operator
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Release.Name }}
          port: {{ .Values.ports.http.port }}
  hostnames:
  - {{ .Values.ingress.host }}
{{ end }}
{{ end }}