{{ if .Values.ingress.enabled }}
{{ if eq .Values.ingress.provider "traefik" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.ingress.host }}`)
    kind: Rule
    services:   
    - kind: TraefikService
      name: {{ .Release.Name }}
    priority: 200
{{ end }}
{{ end }}