apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stable
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app:  {{ .Release.Name }}
  ports:
  {{ range $portName, $portConfig := .Values.ports -}}
  - port: {{ $portConfig.port }}
    targetPort: {{ $portConfig.port }}
    name: {{ $portName }}
  {{ end }}
