{{ if .Values.metrics.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: {{ .Release.Name }}
spec:
  endpoints:
  - interval: 30s
    targetPort: {{ .Values.ports.http.port }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
{{ end }}