{{ if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-ns-suspender
spec:
  dnsNames:
    - {{ .Values.certificate.dnsName }}
  secretName: {{ .Values.certificate.dnsName }}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuer }}
    kind: ClusterIssuer
{{ end }}