# Override this with real Pangoling config!
config:
  a: 1
  b: 2

pangolin:
  image:
    registry: fosrl
    repository: pangolin
    tag: 1.5.1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  ports:
    - name: external
      containerPort: 3000
      # nodePort: 30000  # Optional: NodePort for external access (30000-32767)
    - name: internal
      containerPort: 3001
      # nodePort: 30001  # Optional: NodePort for internal access (30000-32767)
    - name: next
      containerPort: 3002
      # nodePort: 30002  # Optional: NodePort for next service (30000-32767)

persistence:
  # storageClass:
  size: 1Gi

