image:
  repository: 
  tag:

name:

resources:  
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

imagePullSecrets: []

# -- Options: deployment | rollout
controller: deployment

args: []

secrets: 
  enabled: true

# port: 8088

ingress:
  enabled: false
  type: kong
  
# Those maps to configMap
envs: {}
  # KEY: VALUE

# Those maps to env key in pod
env: {}

rabbitmq:
  enabled: false
  vhost:
    name: "/"
    create: false
  user:
    create: true
    username: ""
    password: ""
  # queue:
  #   name:
  #   create: true
  # cluster:
  #   name:
  #   namespace:

init:
  enabled: false
  command: 
  - river 
  args:
  - migrate-up 
  - --database-url 
  - "$DATABASE_URL"