image:
  repository: 
  tag:

name:

resources:  
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

imagePullSecrets: []

# -- Options: deployment | rollout
controller: deployment

args: []

secrets: 
  enabled: true

envs: {}
  # KEY: VALUE