apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerbil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerbil
  template:
    metadata:
      labels:
        app: gerbil
    spec:
      containers:
        - name: gerbil
          {{- with .Values.gerbil.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.gerbil.image.registry }}/{{ .Values.gerbil.image.repository }}:{{ .Values.gerbil.image.tag }}"
          {{- with .Values.gerbil.ports }}
          ports:
          {{- range . }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
              {{- if .hostPort }}
              hostPort: {{ .hostPort }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.gerbil.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - name: config
              mountPath: /var/config
      volumes:
        - name: config
          emptyDir: {}
