apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-envs
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 1h
  dataFrom:
  - extract:
      key: /{{ .Values.environment }}/{{ .Values.name }}
  target:
    name: {{ .Release.Name }}-envs