image:
  repository: witcherek7/gfun
  tag: 0.0.6

env:
  GFUN_POSTGRESQL_HOST: postgresql-rw
  GFUN_POSTGRESQL_DATABASE: gfun
  GFUN_POSTGRESQL_USERNAME: gfun
  GFUN_POSTGRESQL_PASSWORD: gfun
  GFUN_POSTGRESQL_PORT: 5432
  GFUN_TELEMETRY_ENABLED: "false"
  GFUN_TELEMETRY_COLLECTOR_ENDPOINT: "none"

  GFUN_CRON_ENABLED: "false"

  # this must be without GFUN_ prefix
  FAKTORY_URL: tcp://:password@faktory.faktory.svc:7419

  GFUN_MEMPHIS_ENABLED: "false"
  GUFN_MEMPHIS_HOST: ""
  GFUN_MEMPHIS_USERNAME: ""
  GFUN_MEMPHIS_PASSWORD: ""

service:
  main:
    ports:
      http:
        port: 5000