name: dashy
apiVersion: v2
appVersion: 2.1.1
version: 1.0.0
maintainers:
- name: Krzysztof Wiatrzyk
  email: krzwiatrzyk@protonmail.com
sources:
- https://dashy.to
- https://github.com/Lissy93/dashy
keywords:
  - "dashy"
annotations:
  "artifacthub.io/changes": |
    - kind: added
      description: configuration storage as PVC 
    - kind: added
      description: custom readiness check
kubeVersion: ">1.16.0"
icon: https://dashy.to/img/dashy.png
dependencies:
- name: common
  version: "~4.3.0"
  repository: https://library-charts.k8s-at-home.com