name: dashy
apiVersion: v2
appVersion: 2.0.3
version: 0.0.2
maintainers:
- name: Krzysztof Wiatrzyk
  email: krzwiatrzyk@protonmail.com
sources:
- https://dashy.to
- https://github.com/Lissy93/dashy
keywords:
  - "dashy"
annotations:
  "artifacthub.io/prerelease": "true"
  "artifacthub.io/changes": |
    - kind: fixed
      description: README.md file
kubeVersion: ">1.16.0"
icon: https://dashy.to/img/dashy.png
dependencies:
- name: common
  version: "~4.3.0"
  repository: https://library-charts.k8s-at-home.com