{{ if .Values.rabbitmq.enabled }}
{{ if .Values.rabbitmq.user.create }}
{{ if .Values.rabbitmq.user.username}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  username: {{ .Values.rabbitmq.user.username | b64enc }}
{{ end }}
{{ end }}
{{ end }}