{{ if .Values.rabbitmq.enabled }}
{{ if .Values.rabbitmq.vhost.create }}
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: {{ .Release.Name }}
spec:
  name: {{ .Values.rabbitmq.vhost.name | quote }}
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmq.cluster.name | quote }}
    namespace: {{ .Values.rabbitmq.cluster.namespace }}
{{ end }}
{{ end }}