name: casdoor
apiVersion: v2
appVersion: v1.224.0
version: 1.0.0
maintainers:
- name: Krzysztof Wiatrzyk
  email: krzwiatrzyk@protonmail.com
sources:
- https://hub.docker.com/r/casbin/casdoor/tags
- https://github.com/casdoor/casdoor
keywords:
  - "casdoor"
kubeVersion: ">1.16.0"
icon: https://casdoor.org/img/casbin.svg
dependencies:
- name: common
  version: "~4.3.0"
  repository: https://library-charts.k8s-at-home.com