apiVersion: v1
kind: Service
metadata:
  name: pangolin
spec:
  type: ClusterIP
  ports:
    {{- range .Values.pangolin.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    app: pangolin