{{- if .Values.zitadel.dbSslRootCrt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-ssl-root-crt
stringData:
  ca.crt: |-
{{ .Values.zitadel.dbSslRootCrt | default "" | nindent 6 }}
{{- end }}