apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "..fullname" . }}-pvc
    labels:
        {{- include "..labels" . | nindent 4 }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.storage.size | default "1Gi" }}
    {{- if .Values.storageClass }}
    storageClassName: {{ .Values.storage.storageClass }}
    {{- end }}