apiVersion: v2
name: ToolJet
version: 0.0.2
sources:
- https://tooljet.com
- https://github.com/tooljet/tooljet
maintainers:
  - name: Krzwiatrzyk
    email: krzwiatrzyk@protonmail.com
keywords:
  - "tooljet"
annotations:
  "artifacthub.io/prerelease": "true"