# Default user, password with seed init (npm run db:seed): dev@tooljet.io/password

image:
  repository: tooljet/tooljet-ce
  tag: v1.13.3

args:
- "npm"
- "run"
- "start:prod"

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

env:
  PG_HOST: "tooljet-postgresql"
  PG_USER: '{{ .Values.postgresql.auth.username }}'
  PG_PASS: '{{ .Values.postgresql.auth.password }}'
  PG_DB: '{{ .Values.postgresql.auth.database }}'
  # Result of: openssl rand -hex 32
  LOCKBOX_MASTER_KEY: 183f0811f07b4c83428ce2931c245b30bec41e8ad75879de4ed2d55c5bfd2a83
  # Result of: openssl rand -hex 64
  SECRET_KEY_BASE: c42668b1d76fcce93acac8efbb8c62695dfba9960777e7ab89d6b8d43fb703345d98cf563c9f97676b09cfbc9b99e9dacef265075ae9fbb6fe0e6e141bd0210e
  TOOLJET_HOST: 'https://{{ index .Values.ingress.main.hosts 0 "host" }}'
  
resources:
  limits:
    memory: "2000Mi"
    cpu: "2000m"
  requests:
    memory: "1000Mi"
    cpu: "1000m"

probes:
  liveness:
    enabled: false

  readiness:
    enabled: true
    custom: false
    type: TCP
    spec:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 6

postgresql:
  # resources:
  #   requests:
  #     memory: 1Gi
  #     cpu: 500m
  #   limits:
  #     memory: 2Gi
  #     cpu: 2
  auth:
    postgresPassword: postgres
    username: tooljet
    password: tooljet
    database: tooljet


ingress:
  main:
    enabled: false
    primary: true
    autoLink: true
    enableFixedMiddlewares: false
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: tooljet.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix