ingress:
  main:
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
    enabled: true
    hosts:
      - host: argus.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
securityContext:
  readOnlyRootFilesystem: false
persistence:
  config:
    objectName: pav-argus-config
    mountPath: /config
command:
- "/bin/sh"
- "-c"
- "cp /config/config.yml /etc/argus/config.yml && /bin/argus -config.file=/etc/argus/config.yml"
# lifecycle:
#   postStart:
#     exec:
#       command: ["/bin/sh", "-c", "cp /config/config.yml /etc/argus/config.yml"]

config:
  service:
    dani-garcia/vaultwarden:
      type: github
      url: dani-garcia/vaultwarden
      web_url: https://github.com/dani-garcia/vaultwarden/releases/{{ version }}
      icon: https://raw.githubusercontent.com/dani-garcia/vaultwarden/main/src/static/images/vaultwarden-icon.png
      deployed_version:
        url: http://pav:5000/versions/vaultwarden
        regex: ([0-9.]+)

    louislam/uptime-kuma:
      type: github
      url: louislam/uptime-kuma
      web_url: https://github.com/louislam/uptime-kuma/releases/{{ version }}
      icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
      deployed_version:
        url: http://pav:5000/versions/uptimekuma
        regex: ([0-9.]+)

    minio:
      semantic_versioning: false
      regex_version: (.*)
      type: github
      url: minio/minio
      web_url: https://github.com/minio/minio/releases/{{ version }}
      icon: https://raw.githubusercontent.com/minio/minio/master/.github/logo.svg?sanitize=true
      deployed_version:
        url: http://pav:5000/versions/minio
        regex: (.*)

extensions:
  pav: false

pav:
  apps:
    vaultwarden: 1.0.0
    uptimekuma: 0.11.0
    minio: RELEASE.2020-08-08T02-33-58Z
