config:
  # service:
  #   dani-garcia/vaultwarden:
  #     type: github
  #     url: dani-garcia/vaultwarden
  #     web_url: https://github.com/dani-garcia/vaultwarden/releases/{{ version }}
  #     icon: https://raw.githubusercontent.com/dani-garcia/vaultwarden/main/src/static/images/vaultwarden-icon.png
  #     deployed_version:
  #       url: https://vaultwarden.example.io/api/version
  #       regex: ([0-9.]+)

configmap:
  config:
    enabled: true
    data: 
      config.yml: | 
        {{- .Values.config | toYaml | nindent 2 }}

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
securityContext:
  readOnlyRootFilesystem: false

persistence:
  config:
    enabled: true
    type: configMap
    mountPath: /config
    name: argus-config

image:
  repository: releaseargus/argus
  tag: 0.11.0

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 8080
  
resources:
  limits:
    memory: "256Mi"
    cpu: "200m"
  requests:
    memory: "128Mi"
    cpu: "100m"

probes:
  liveness:
    enabled: false

  readiness:
    enabled: false
 
  startup:
    enabled: false

command:
- "/bin/sh"
- "-c"
- "cp /config/config.yml /etc/argus/config.yml && /bin/argus -config.file=/etc/argus/config.yml"