config: |
  service:
    release-argus/argus:
      latest_version:
        type: github
        url: release-argus/argus
      dashboard:
        icon: https://github.com/release-argus/Argus/raw/master/web/ui/static/favicon.svg
        icon_link-to: https://release-argus.io
        web_url: https://github.com/release-argus/Argus/blob/master/CHANGELOG.md

configmap:
  config:
    enabled: true
    data: 
      config.yml: |
        {{- .Values.config | nindent 2 }}

persistence:
  data:
    enabled: true
    type: pvc
    mountPath: /app/data
    size: 1Gi
  config:
    enabled: true
    type: configMap
    mountPath: /config
    name: argus-config

image:
  repository: releaseargus/argus
  tag: 0.11.0

service:
  main:
    ports:
      http:
        port: 8080
  
resources:
  limits:
    memory: "256Mi"
    cpu: "200m"
  requests:
    memory: "128Mi"
    cpu: "100m"

probes:
  liveness:
    enabled: false

  readiness:
    enabled: false
 
  startup:
    enabled: false

command:
- "/bin/sh"
- "-c"
- "argus -config.file=/config/config.yml"