apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zitadel-masterkey
stringData:
  zitadel-masterkey: {{ required "A valid .Values.zitadel.masterkey entry is required!" .Values.zitadel.masterkey }}
