# Default user, password: dev@tooljet.io/password

custom:
  host: ohmyform.localhost

image:
  repository: ohmyform/ohmyform
  tag: 1.0.3

service:
  main:
    ports:
      http:
        port: 3000
        targetPort: 3000

env:
  CREATE_ADMIN: "TRUE"
  ADMIN_EMAIL: admin@local.host
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin
  DATABASE_DRIVER: sqlite
  DATABASE_URL: "sqlite:///data/data.sqlite"
  MAILER_URI: smtp://local.host
  LOGIN_NOTE: "Either login with admin:admin or create your own account to test OhMyForm"
  
resources:
  limits:
    memory: "500Mi"
    cpu: "500m"
  requests:
    memory: "250Mi"
    cpu: "100m"

probes:
  liveness:
    enabled: false

  readiness:
    enabled: true
    custom: false
    spec:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 6

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "{{ .Values.custom.host }}"
        paths:
          - path: /
            pathType: Prefix

persistence:
  data:
    enabled: true
    type: pvc
    mountPath: /data
    size: 1Gi
    accessMode: ReadWriteOnce
    # storageClass:
