config:
  server:
    port: 8080
    address: 0.0.0.0
  featureFlags:
    enabled: false
    provider: "growthbook"
    growthbook:
      host:
      key: 

image:
  repository: c8n.io/krzwiatrzyk/gmod
  tag: 0.0.1

ports:
  http:
    port: 8080

resources:  
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

environment: default

imagePullSecrets: []

# -- Options: deployment | rollout
controller: deployment

args: []

metrics:
  enable: true

ingress:
  enabled: true
  host: gmod.staging.windkube.com
  # Available: nginx | traefik
  provider: nginx