config:
  server:
    port: 8080
    address: 0.0.0.0

image:
  repository: c8n.io/krzwiatrzyk/gmod
  tag: 0.0.1

ports:
  http:
    port: 8080

resources:  
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

imagePullSecrets: []
