{{- range index .Values "namespaces" }}
---
{{ if .enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  annotations:
    {{ if .suspender -}}
    kube-ns-suspender/controllerName: kube-ns-suspender
    {{ end }}
{{- end }}
{{- end }}