{{- range index .Values "namespaces" }}
---
{{ if .enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .name }}-viewers
  namespace: {{ .name }}
subjects:
  {{- range .viewers }}
  - kind: ServiceAccount
    name: {{ . }}
    namespace: users
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{- end }}
{{- end }}

