name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.1

      - name: Add k8s-at-home repo
        run: helm repo add k8s-at-home https://library-charts.k8s-at-home.com

      - name: Add truecharts repo
        run: helm repo add truecharts https://library-charts.truecharts.org

      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami 

      - name: Add krzwiatrzyk repo
        run: helm repo add krzwiatrzyk https://krzwiatrzyk.github.io/charts/

      - name: Add cockroach repo
        run: helm repo add cockroachdb https://charts.cockroachdb.com/

      - name: Add repos
        run: |
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true