name: Release changed charts to S3
on:
  workflow_dispatch:
  # push:
  #   branches:
  #   -  master
  #   paths:
  #   - charts/**


permissions:
    id-token: write
    contents: read
env:
    AWS_ACCOUNT_ID: 
    AWS_REGION: eu-west-1
    AWS_BUCKET: windkube-charts
    AWS_ROLE: chart-releaser
    
jobs:
  generate-matrix:
    outputs:
      list: ${{ steps.list.outputs.list }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40.2.1
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 2
  
      - name: Show changes
        id: list
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          echo ${{ steps.changed-files.outputs.all_changed_files }} | tr " " "\n" | grep charts | xargs -n 1 basename | tr "\n" " " | jq -R -s -c 'split(" ")[:-1]' > res.json
          echo "list<<EOF" >> $GITHUB_OUTPUT
          cat res.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  template:
    runs-on: ubuntu-latest
    needs: 
    - generate-matrix
    strategy:
      matrix:
        chart: ${{ fromJson(needs.generate-matrix.outputs.list) }}
    defaults:
      run:
        working-directory: charts/${{ matrix.chart }}
    steps:
    - uses: actions/checkout@v3
    - name: Update dependencies
      run: helm dependency update
    - name: Helm template
      run: >
        test -f values-test.yaml &&
        helm template . -f values-test.yaml || 
        helm template . 
  package:
    runs-on: ubuntu-latest
    needs: 
    - generate-matrix
    strategy:
      matrix:
        chart: ${{ fromJson(needs.generate-matrix.outputs.list) }}
    defaults:
      run:
        working-directory: charts/${{ matrix.chart }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-helm@v3
      with:
        version: v3.12.3
    - name: Update dependencies
      run: helm dependency update
    - name: Helm package
      run: helm package .
    - name: Get package name
      id: file
      run: echo name=$(ls | grep .tgz) >> $GITHUB_OUTPUT
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.chart }}
        path: charts/${{ matrix.chart }}/${{ steps.file.outputs.name }}
        retention-days: 1
  release:
    env:
      HELM_S3_MODE: 3
    runs-on: ubuntu-latest
    needs: 
    - generate-matrix
    - package
    - template
    strategy:
      matrix:
        chart: ${{ fromJson(needs.generate-matrix.outputs.list) }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/oidc/${{ env.AWS_ROLE }}
        role-session-name: ${{ env.AWS_ROLE }}-${{ github.run_id }}
        aws-region: ${{ env.AWS_REGION }}
    - uses: azure/setup-helm@v3
      with:
        version: v3.12.3
    - name: Install Helm S3 Plugin
      run: helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.15.1 
    - name: Create index
      run: helm s3 init s3://${{ env.AWS_BUCKET }}/charts --ignore-if-exists
    - name: Add Helm repo
      run: helm repo add ${{ env.AWS_BUCKET }} s3://${{ env.AWS_BUCKET }}/charts
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.chart }}
    - name: Get package name
      id: file
      run: |
        echo name=$(ls | grep .tgz) >> $GITHUB_OUTPUT
    
    - name: Push chart
      run: helm s3 push ./${{ steps.file.outputs.name }} ${{ env.AWS_BUCKET }} --ignore-if-exists

  reindex:
    env:
      HELM_S3_MODE: 3
    runs-on: ubuntu-latest
    needs: 
    - release
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/oidc/${{ env.AWS_ROLE }}
        role-session-name: ${{ env.AWS_ROLE }}-${{ github.run_id }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Install Helm S3 Plugin
      run: helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.15.1 

    - name: Create index
      run: helm s3 init s3://${{ env.AWS_BUCKET }}/charts --ignore-if-exists

    - name: Add Helm repo
      run: helm repo add ${{ env.AWS_BUCKET }} s3://${{ env.AWS_BUCKET }}/charts

    - name: Reindex
      run: helm s3 reindex ${{ env.AWS_BUCKET }}