name: Release charts to S3

on:
  workflow_dispatch:
  push:
    branches:
    -  main
    paths:
    - charts/**

jobs:
  generate-matrix:
    outputs:
      list: ${{ steps.list.outputs.list }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: list
      run: |
        ls -m charts | tr -d "," | tr "\n" " " | jq -R -s -c 'split(" ")[:-1]' > res.json
        echo "list<<EOF" >> $GITHUB_OUTPUT
        cat res.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

  release-charts:
    runs-on: ubuntu-latest
    needs: 
    - generate-matrix
    strategy:
      matrix:
        chart: ${{ fromJson(needs.generate-matrix.outputs.list) }}
    defaults:
      run:
        working-directory: charts/${{ matrix.chart }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::506534868111:role/oidc/helm-s3
        role-session-name: helm-s3-${{ github.run_id }}
        aws-region: eu-central-1

    - uses: actions/checkout@v3
    - run: ls